project:
  type: website

website:
  title: "Dr D's Teaching Data"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: readable
    
execute:
  freeze: auto # re-render only when source changes
  echo: false
  warning: false

