project:
  type: website
  output-dir: docs
  
website:
  title: "Dr D's Teaching Data"
  navbar:
    left:
      - href: index.qmd
        text: All data

format:
  html:
    theme: readable
    
execute:
  freeze: auto # re-render only when source changes
  echo: false
  warning: false

