---
output: 
  html_document: 
    theme: readable
    
params: 
  data_name: 
    value: name
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE, eval=TRUE)
options(knitr.kable.NA = '')

library(tidyverse)
library(rvest)
library(knitr); library(kableExtra)
library(downloadthis)

#params <- list(data_name = "ames") # for testing
```

```{r}
file.name <- paste0(params$data_name, ".csv")
#file.name <- paste0("MATH105/", params$data_name, ".csv") # for testing
download.path <- paste0("https://github.com/norcalbiostat/teaching_data/tree/main/MATH105/", file.name)
# get data, convert all character to factor
dta <- read.csv(file.name) %>% 
  mutate(across(where(is.character), factor))

colnames(dta) <- gsub("\\.", "_", colnames(dta))

# get metadata from web codebook
label_url <- paste0("https://www.openintro.org/data/index.php?data=",
                    params$data_name)

# header 1
dta.header <- read_html(label_url) %>%
  html_elements("h1") %>%
  html_text2() 

# description
dta.desc.all <- read_html(label_url) %>%
  html_elements("p")%>%
  html_text2()

x <- grep("Return to", dta.desc.all)
dta.desc <- dta.desc.all[x+1]


# variable labels
html.to.dta <- read_html(label_url) %>%
  html_elements("dl") %>%
  html_text2() %>%
  str_split(pattern = "\n\n") %>%
  unlist() %>% data.frame()


# split variables and labels
odd <- seq_len(nrow(html.to.dta)) %% 2 ==1

# start to create metadata summary file
metadata <- data.frame(
  var = html.to.dta[odd, 1], 
  label = html.to.dta[!odd, 1]) %>% 
  mutate(percent_missing_obs = round(colSums(is.na(dta))/NROW(dta), 2)*100, 
         var = gsub("\\.", "_", var))

# get levels of factor vars. Assign data type to cat data
factor.levels <- dta %>% 
  select(where(is.factor)) %>% 
  purrr::map_dfr(function(f) {
    data.frame(Levels = levels(f))
  }, .id = "var") %>%
  filter(Levels !="") %>%
  group_by(var) %>% 
  summarise_all(paste, collapse = ', ') %>%
  mutate(data_type = "Categorical")

# get range of numeric vars. Assign data type to numeric data
numeric.ranges <- dta %>%
  select(!where(is.factor)) %>% 
  map_df(.f = ~ broom::tidy(summary(.x)), .id = "variable") %>%
  mutate(range = paste0("[", minimum, ", ", maximum, "]")) %>% 
  select(var = variable, range)

# left join factor levels onto metadata, assign data type to numeric data
metadata_out <- metadata %>% 
  left_join(factor.levels) %>%
  left_join(numeric.ranges) %>%
  mutate(data_type = ifelse(is.na(Levels), "Numeric", data_type), 
         values = ifelse(!is.na(Levels), Levels, range)) %>%
  select(variable = var, label, 
         `Percent Missing Observations` = percent_missing_obs,
         data_type, `Plausible Values` = values)

```

---
title: "Codebook for `r dta.header`"
---

## Description

`r dta.desc`

Learn more about where this data came from at `r label_url`. Note, not all data sets have additional information. 

```{r}
download_file(
  path = download.path, 
  link = file.name,
  button_label = "Download file",
  button_type = "primary",
  has_icon = TRUE,
  icon = "fa fa-save",
  self_contained = FALSE
)
```

<a href = "https://norcalbiostat.github.io/teaching_data/"> <button type="button" class="btn btn-warning">Back to all data</button> </a>

```{r}
kbl(metadata_out) %>%
  kable_styling(full_width=F, fixed_thead = T) %>% 
  column_spec(1, bold = T, border_right = T) %>%
  column_spec(2, width = "30em") %>% 
  column_spec(5, width = "30em") 
```
